### ISSUE TITLE
ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### ISSUE THREAD

**Issue by oscard0m** [oscard0m/octoherd-script-add-cache-to-node-github-action#9]
ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

i.e.:
* `octokit/sandbox`
* `probot/sandbox`

**Comment by oscard0m** [comment]
@gr2m Do you know what do these 2 repos have in common? Any kind of restriction I should be aware of?

**Comment by gr2m** [comment]
maybe `probot/sandbox` has no `actions/setup-node` step, and `octokit/sandbox` has `actions/setup-node@v2-beta` which the script might not find?

**Comment by oscard0m** [comment]
Tried to fork `octokit/sandbox` and in my fork worked. When running it step by step it I get a 422 error `HttpError: Reference already exists` but checking branches in that repo I don't see any existing branches. Could be some permission issue? @gr2m  (in any case, I just opened the PR from my fork)

**Comment by gr2m** [comment]
what was the problem?

**Comment by oscard0m** [comment]
@gr2m reopened issue since it's happening to both. I will put a debugger but I don't want to add noise to `probot` or `octokit`, any idea on how to do it?

**Comment by gr2m** [comment]
I'd create a repository which replicates the problem. You said it works when you fork the repository?

Can you share the error logs for one of the runs that failed with that error?

**Comment by oscard0m** [comment]
> I'd create a repository which replicates the problem. You said it works when you fork the repository?
> 
> Can you share the error logs for one of the runs that failed with that error?

<details><summary>Error Stack</summary>
<p>

#### yes, even hidden code blocks!

```javascript
{"repository":{"id":319783314,"owner":{"login":"probot","id":26350515,"node_id":"MDEyOk9yZ2FuaXphdGlvbjI2MzUwNTE1","avatar_url":"https://avatars.githubusercontent.com/u/26350515?v=4","gravatar_id":"","url":"https://api.github.com/users/probot","html_url":"https://github.com/probot","followers_url":"https://api.github.com/users/probot/followers","following_url":"https://api.github.com/users/probot/following{/other_user}","gists_url":"https://api.github.com/users/probot/gists{/gist_id}","starred_url":"https://api.github.com/users/probot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/probot/subscriptions","organizations_url":"https://api.github.com/users/probot/orgs","repos_url":"https://api.github.com/users/probot/repos","events_url":"https://api.github.com/users/probot/events{/privacy}","received_events_url":"https://api.github.com/users/probot/received_events","type":"Organization","site_admin":false},"name":"sandbox"},"msg":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at Function.from (buffer.js:333:9)\n    at addCacheToSetupNodeStep (file:///Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/utils/yaml-parser.js:44:14)\n    at /Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/node_modules/octokit-plugin-create-pull-request/dist-node/index.js:134:24\n    at async Promise.all (index 0)\n    at async createTree (/Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/node_modules/octokit-plugin-create-pull-request/dist-node/index.js:89:17)\n    at async composeCreatePullRequest (/Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/node_modules/octokit-plugin-create-pull-request/dist-node/index.js:263:35)\n    at async Object.script (file:///Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/script.js:70:21)\n    at async runScriptAgainstRepositories (file:///Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/node_modules/@octoherd/cli/lib/run-script-against-repositories.js:64:9)\n    at async octoherd (file:///Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/node_modules/@octoherd/cli/index.js:114:3)\n    at async run (file:///Users/XXX/.npm/_npx/98420/lib/node_modules/octoherd-script-add-cache-to-node-github-action/node_modules/@octoherd/cli/bin/run.js:22:5)","code":"ERR_INVALID_ARG_TYPE","level":"error","time":1626637079234}
```

</p>
</details>

**Comment by oscard0m** [comment]
Ok I found the issue. Since I don't have `push` rights for `octokit/sandbox` and for `probot/sandbox` I was getting a collision of forks in my personal account:

Originally, I had a for from `gr2m/sandbox` and that was originating `sandbox-1` and `sandbox-2` fork creation. Today I removed my fork from `gr2m/sandbox` so I stopped having issues with `oscard0m/sandbox` (octokit) but still having problems with `oscard0m/sandbox-probot`. After removing the fork from octokit, the issue has been solved.

Sounds like a super edge case which I'm  not sure if we should invest on fixing. What do you think?

**Comment by gr2m** [comment]
Agreed
